
train:
  _target_: src.datasets.LJSpeechDataset
  root: /kaggle/working/dla_hw3      
  segment_size: 8192
  sampling_rate: 22050
  return_text: false

inference:
  _target_: src.datasets.LJSpeechDataset
  root: /kaggle/working/dla_hw3
  segment_size: 8192
  sampling_rate: 22050
  return_text: false
