_target_: src.model.HiFiGAN

in_channels: 80
lambda_mel: 45.0
lambda_fm: 2.0

mel_config:
  _target_: src.model.MelSpectrogramConfig
  sr: 22050
  win_length: 1024
  hop_length: 256
  n_fft: 1024
  f_min: 0
  f_max: 8000
  n_mels: 80
  power: 1.0
