defaults:
  - model: hifigan          
  - writer: cometml
  - metrics: empty        
  - datasets: ljspeech      
  - dataloader: example
  - transforms: none
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}

loss_function:
  _target_: src.loss.HiFiGANLoss

trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 500
  device_tensors: ["audio", "mel"]  
  resume_from: null
  device: cuda
  override: True
  monitor: "min loss"               
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
