_target_: src.logger.CometMLWriter

project_name: "dla_hw3_hifigan"   
workspace: null                  
run_name: "hifigan_baseline"
mode: "online"

loss_names:
  - loss
  - loss_d
  - loss_g
  - loss_mel
  - loss_fm
  - loss_adv

log_checkpoints: True   # пусть Comet хранит чекпоинты
id_length: 32
